title: Technical Enablement
description: Public content
remote_theme: clarkhacks/Minimal-Text
logo: https://raw.githubusercontent.com/redislabs-training/redislabs-training.github.io/master/img/logo.png
